### ISSUE TITLE
public looks

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/tc-reporting-api#4]
Define config for making specific looks publicly accessible.

**Comment by ajefts** [comment]
@skyhit Is this something I can do with config?  Basically, I want to be able to say look 412 can be accessed by anybody...

**Comment by skyhit** [comment]
no, currently, it is not supported.  should we have a separate endpoint for this purpose, or reuse the existing one?

**Comment by ajefts** [comment]
Seems like we should reuse the same one, right?

**Comment by skyhit** [comment]
yeah, let me run a F2F challenge

**Comment by ajefts** [comment]
ok
