### ISSUE TITLE
Circle CI unable to build 

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/tc-reporting-api#75]
Circle CI is unable to build the tc-reporting-api module.

**Comment by m-yadav** [comment]
@Gunasekar-K Can you please help here. has there been any changes as the automated process is not able to build the module.

**Comment by m-yadav** [comment]
@Gunasekar-K can you please help here

**Comment by Gunasekar-K** [comment]
Issue fixed.As part of jessie upgrade, few packages are installed. Thos packages are installed again. After clean up the extra package installation, it fixed automatically
