### ISSUE TITLE
Dev Deployement Failed

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/tc-reporting-api#79]
Hi @Gunasekar-K 

Dev deployment has failed to the repo again .
https://app.circleci.com/pipelines/github/topcoder-platform/tc-reporting-api/28/workflows/efdf664f-efe9-4ed6-b26c-5365694354f6/jobs/309

Can you please check and help here .

**Comment by Gunasekar-K** [comment]
Updated build image to fix aws cli install issue
